# Generated by Django 4.2.29 on 2026-04-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_order_id', models.CharField(max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('SL_MARKET', 'SL Market')], max_length=15)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=5)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('FILLED', 'Filled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('is_paper', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('gross_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('trading_halted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('instrument_type', models.CharField(choices=[('EQUITY', 'Equity'), ('INDEX_FUTURES', 'Index Futures')], default='EQUITY', max_length=20)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('lot_size', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('max_quantity', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('EMA_CROSSOVER', 'EMA Crossover'), ('ORB', 'Opening Range Breakout'), ('VWAP_BOUNCE', 'VWAP Bounce')], max_length=30)),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('EXIT_LONG', 'Exit Long'), ('EXIT_SHORT', 'Exit Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('candle_timestamp', models.DateTimeField()),
                ('acted_on', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading.watchlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('EMA_CROSSOVER', 'EMA Crossover'), ('ORB', 'Opening Range Breakout'), ('VWAP_BOUNCE', 'VWAP Bounce')], max_length=30)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SL_HIT', 'Stop Loss Hit'), ('TARGET_HIT', 'Target Hit')], default='OPEN', max_length=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('entry_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_positions', to='trading.order')),
                ('exit_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_positions', to='trading.order')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.watchlist')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.signal'),
        ),
        migrations.CreateModel(
            name='OHLCVCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('vwap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='trading.watchlist')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='trading_ohl_symbol__f4b36e_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
