# Generated by Django 4.2.29 on 2026-04-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRiskSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('suggested_size_multiplier', models.FloatField(default=1.0)),
                ('reason', models.TextField()),
                ('portfolio_exposure_pct', models.FloatField(default=0.0)),
                ('recent_win_rate', models.FloatField(default=0.0)),
                ('recent_drawdown', models.FloatField(default=0.0)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AITunerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField()),
                ('strategy', models.CharField(choices=[('EMA_CROSSOVER', 'EMA Crossover'), ('ORB', 'Opening Range Breakout'), ('VWAP_BOUNCE', 'VWAP Bounce'), ('ALL', 'All Strategies')], max_length=30)),
                ('suggestion_text', models.TextField()),
                ('current_param', models.CharField(blank=True, max_length=100)),
                ('suggested_param', models.CharField(blank=True, max_length=100)),
                ('win_rate_this_week', models.FloatField(default=0.0)),
                ('net_pnl_this_week', models.FloatField(default=0.0)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_ending'],
            },
        ),
        migrations.CreateModel(
            name='AISignalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.IntegerField(default=0)),
                ('market_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], default='NEUTRAL', max_length=20)),
                ('sentiment_reason', models.TextField(blank=True)),
                ('avoid_symbol', models.BooleanField(default=False)),
                ('timeframe_aligned', models.BooleanField(default=False)),
                ('volume_above_avg', models.BooleanField(default=False)),
                ('strategy_recent_winrate', models.FloatField(default=0.0)),
                ('passed_gate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score', to='trading.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField()),
                ('what_worked', models.TextField(blank=True)),
                ('what_failed', models.TextField(blank=True)),
                ('lesson', models.TextField(blank=True)),
                ('market_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_journal', to='trading.position')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
